coomer:
  session: ''
gofile:
  api_key: ''
imgur:
  client_id: ''
jdownloader:
  device: ''
  password: ''
  username: ''
kemono:
  session: ''
meganz:
  email: ''
  password: ''
pixeldrain:
  api_key: ''
realdebrid:
  api_key: ''
reddit:
  personal_use_script: ''
  secret: ''
